spring:
  application:
    name: ${SPRING_APP_NAME:oauth-Server}
  profiles:
    active: prod
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/test?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:auth_db}?${DB_PARAMS:useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mysql}
  sql:
    init:
      mode: ALWAYS
#      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: ALWAYS
      console-available: true

  docker:
    compose:
      enabled: ${DOCKER_INITIALIZATION:false}


logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.boot.docker.compose: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: ${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}

# ==============================
# Security Matchers
# ==============================
security:
  jwt:
    secret:  ${SECURITY_JWT_SECRET:superSecretKey12345678901234567890}
  endpoints:
    public-matchers:
      - /register
      - /login
    role-based:
      - path: /admin/**
        roles:
          - ADMIN
      - path: /user/**
        roles:
          - USER
          - ADMIN

server:
  port: ${AUTH_SERVER_PORT:8081}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://192.168.1.5:3000,http://localhost:3000, http://100.125.57.120:3000}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
  exposed-headers:
    - Authorization
    - "Content-Length"
    - "Content-Range"
  allow-credentials: true
